### PR TITLE
fix: Leumi login selector

### PR DESCRIPTION
**Pull request by itairaz1**

### CODE REVIEW

**Comment by michlus** [comment]
So does that mean that it's fixed for Bank Leumi?
Is it already released?
I just installed the latest version as of yesterday (v1.20.0) and I still have the issue.
Thanks.

**Comment by itairaz1** [comment]
@michlus It is Pull Request that is pending approval in order to fix the issue. When it will be approve it will be merge and release in the next version

**Comment by michlus** [comment]
@itairaz1 got it; thank you very much.

**Comment by michlus** [comment]
Hi.
Does anyone know when this fix is going to be released?
It's already some 45 days that I can't pull any transactions from Leumi Bank.
Since I guess it's a generic problem for everyone, I wonder how people manage.
Thanks.

**Review by baruchiro — APPROVED** [review]
Hi, I approve this change.

Most of the time we prefer to hear the problem is reproduced for more users, and there is another one except you that this change is working for him.

**Comment by michlus** [comment]
Thanks very much.
I ignore why it wasn’t a problem for all users , but anyways - I can confirm that the problem is indeed solved.
Thanks !
Michel

________________________________

**Comment by baruchiro** [comment]
I created a list of Code Owners to get PRs verified quickly, you're welcome to join.

See #830

**Pull request merged**
