### PR TITLE
feat(cal): fetch pending transaction

### LINKED ISSUE #791: CAL scraper should retrieve pending transcations
CAL launched a new website this week and surprisingly the scraper is still working.

Previously CAL showed only completed transactions but now on the new website they also show pending transactions.
These pending transactions are currently not returned by the scraper.

The scraper should be updated to retrieve the pending transactions as well.

### PR DESCRIPTION
**Pull request by galbarm**
Fix #791

Pending transactions in CAL, are retrieved via a separate endpoint than the completed transactions.
Added a request to fetch pending transactions from the new endpoint.

### CODE REVIEW

**Comment by galbarm** [comment]
fixes https://github.com/eshaham/israeli-bank-scrapers/issues/791

**Comment by esakal** [comment]
Hi @galbarm thanks for the contribution. I'll quickly play with it soon and if everything works i'll merge it. Thank you for your patience

**Comment by galbarm** [comment]
@esakal any chance you find time for this?

**Review by esakal — APPROVED** [review]

**Comment by esakal** [comment]
@galbarm  sorry for the late response, my availability and access to the computer is small during Jule/Aug.
I'm merging it now
Thanks for the contribution!

**Comment by esakal** [comment]
@eshaham I cannot merge it due to the CI checks for node v16

Can you please merge?

**Comment by eshaham** [comment]
@esakal, this is different - the v16 tests did not run because the branch has not taken the latest code from the `master` branch.
I think that merging from `master` should solve the issue.

**Comment by gbarmashiahflir** [comment]
can this be merged?

**Comment by galbarm** [comment]
@esakal @eshaham can this be merged?

**Comment by esakal** [comment]
@eshaham I managed to merge a PR #811 but this one is still stuck on the checks. Please merge. hopefully new PRs will work also for me

**Comment by eshaham** [comment]
@esakal we need to resolve conflicts first, tried to take a look, but it was a bit confusing.

**Comment by gbarmashiahflir** [comment]
@esakal @eshaham
I can help with the conflicts. What would be the best way?
I can submit a new PR on top of current master. Will it help?

**Comment by galbarm** [comment]
@esakal @eshaham
I can help with the conflicts. What would be the best way?
I can submit a new PR on top of current master. Will it help?

**Review by baruchiro — COMMENTED** [review]
Hi, I solved the conflict, let's just solve the `throw` comment and continue.

**Comment by baruchiro** [comment]
Hi @galbarm, [Call for Code Owners](https://github.com/eshaham/israeli-bank-scrapers/issues/830)

**Comment by idryzhov** [comment]
Important feature, thanks. I just tested it and it works great. But I think the last [commit](https://github.com/eshaham/israeli-bank-scrapers/pull/794/commits/72c83742bcb668598f0bdb6c63ba8fe2c2f2cd1e) by @baruchiro should be reverted, because it breaks TS type checking and we'll still fail later in `convertParsedDataToTransactions`, because it doesn't expect `null` as the first argument and dereferences it right away.

**Comment by baruchiro** [comment]
Thank you @idryzhov, can I add you to the #830?

**Comment by idryzhov** [comment]
> Thank you @idryzhov, can I add you to the #830?

Sure. Cal, Max, Leumi.

**Pull request merged**
