### PR TITLE
add prerelease workflow

### PR DESCRIPTION
**Pull request by esakal**
I admit that @baruchiro infected me with the github actions thing. I found a workflow that can be used to deploy a prerelease version to npm in a smart way and label it with `next` tag. 

@eshaham This might be really handy in our case. Having an automatic process that deploys a temporary `next` version will allow developers to use merged PRs changes immediately instead of waiting for an official release

I marked this PR as draft to consult with you both @eshaham and @baruchiro about the implementation. this workflow is using `epeli/npm-release` action. although it is very popular using others actions, I'm not sure how comfortable I feel to pass the NPM secret (of Elad) to that action. @baruchiro how about coping that action into our own project and using a local copy instead? its' license is MIT so I'm sure it is legit and I think we will feel more secure that way. wdyt? are you using somewhere local actions?

### CODE REVIEW

**Comment by baruchiro** [comment]
First of all, I see that I lit the CI fire ;-)

Now, depending on your preferred way of working, you may want to consider first what system is right for us. In my PRs I use Github Actions, but maybe you want to use TravisCI?
I'm just asking if you would like to start a discussion. If so, you should open it at #146 .

-----
About using `epeli/npm-release`, I'm not familiar with the _prerelease_ pipeline, and also I'm not an expert in GithubActions, but I can say that yes, you can copy the `epeli/npm-release` to your repository.

But I think also there is a way to select a specific version of `epeli/npm-release`. So, if you checked the code in the current version of external action, you can use that version and even if the author will update the Action with bad code, you still use the verified version (but we should check if the author can override a specific version).

**Comment by esakal** [comment]
@baruchiro, CI is something that is in this library roadmap yet adding unit-tests doesn't necessarily serve our needed since the companies endpoints are not predicted. Sure we can mock things and use snapshots, but most of the time it will break due to changes in the endpoints and not as a result of wrong code modifications. So we actually needs end-to-end testing which also has its' issues.

The reason I'm pointing the unit-test / end-to-end thing is that we are not pushing the CI forward till we will decide how to tackle the automatic tests. Without them CI server cannot actually publish to NPM and can cover very limited scenarios. The reason I added this PR is that I actually think that we can benefit from this feature immediately even without tackling the tests issue.

> In my PRs I use Github Actions, but maybe you want to use TravisCI?

Wether using Github Actions or TravisCI is in my opinion something that should be decided by @eshaham. Both will do the trick.

> About using epeli/npm-release, I'm not familiar with the prerelease pipeline, and also I'm not an expert in GithubActions, but I can say that yes, you can copy the epeli/npm-release to your repository.

can you guide me to a good reference or documentation that is using the latest github actions api? I found some examples that were using the former api with `main.workflows` prior to the YAML support.

**Comment by baruchiro** [comment]
https://help.github.com/en/articles/workflow-syntax-for-github-actions#jobsjob_idstepsuses

```yaml
steps:    
  - uses: actions/setup-node@74bc508 # Reference a specific commit
  - uses: actions/setup-node@v1      # Reference the major version of a release   
  - uses: actions/setup-node@v1.2    # Reference a minor version of a release  
  - uses: actions/setup-node@master  # Reference a branch
```

**Comment by esakal** [comment]
@baruchiro thanks for the reference, I modified this PR to reference a specific commit. 

---

@eshaham there are two options:
1. using a specific commit as done in this PR (latest tag [epeli/npm-release@v1.1.1](https://github.com/epeli/npm-release/releases/tag/v1.1.1)).
2. coping the action into our repo and using relative path [as mentioned here](https://help.github.com/en/articles/workflow-syntax-for-github-actions#example-using-action-in-the-same-repository-as-the-workflow). 

I think option one is safe enough based on github actions documentation. see [here](https://help.github.com/en/articles/workflow-syntax-for-github-actions#jobsjob_idstepsuses):
>  ... Using the commit SHA of a released action version is the safest for stability and security. ...

## How to continue with this PR
1. review [epeli/npm-release@v1.1.1 source](https://github.com/epeli/npm-release/blob/bc78fc8caa52fa9541f83b3fbaa2fc9938bdf0ee/src/main.ts)
2. add to github actions `NPM_TOKEN` [see documentation here](https://help.github.com/en/articles/virtual-environments-for-github-actions#creating-and-using-secrets-encrypted-variables)

**Comment by eshaham** [comment]
@esakal I like this, let's try it 😄

**Comment by eshaham** [comment]
@esakal sweet, seems to be working 😄

**Comment by esakal** [comment]
Yesh! this will reduce the pressure of deploying new official commits after every merge :)

**Pull request merged**
