### PR TITLE
Mizrahi support both 'OnlinePilot' and 'Online' API

### PR DESCRIPTION
**Pull request by baruchiro**
Fix: https://github.com/eshaham/israeli-bank-scrapers/pull/748#issuecomment-1396527222

### CODE REVIEW

**Comment by baruchiro** [comment]
@BackSlasher Please check if it work for you.

**Comment by BackSlasher** [comment]
Sure thing.
BTW, how do you check? I manually patch the JS files. I'm not sure how to "fully build" the TS ones

**Comment by BackSlasher** [comment]
Manually patched the compiled JS files and tested. WFM.

**Review by BackSlasher — APPROVED** [review]

**Comment by BackSlasher** [comment]
PS, thanks for not just rolling back my changes, but rather making better code

**Comment by baruchiro** [comment]
> Sure thing. BTW, how do you check? I manually patch the JS files. I'm not sure how to "fully build" the TS ones EDIT: I meant building the JS ones

I'm not sure what you asking. To check my code I'm running the tests in this project.

**Comment by BackSlasher** [comment]
Oh right, good point :)

**Comment by baruchiro** [comment]
@eshaham @esakal I need help with this. I'm not sure why `Promise.any` isn't supported here.

**Comment by esakal** [comment]
Hi @baruchiro please try the following:

try adding the library “es2020.promise” as part of the lib key inside the tsconfig.json file.

```
{
  "compilerOptions": {
    "lib": [
      "es2020.promise"      
    ] 
   // ...
  }
}
```

**Comment by baruchiro** [comment]
@esakal I updated the TypeScript version (and stayed at v3)

**Pull request merged**
