### PR TITLE
fix the network and submit race

### PR DESCRIPTION
**Pull request by esakal**
This pull request is yet another attempt to resolve the navigation issue with visa-cal scraper when using `showBrowser` set to `false`.

@sushi30 @RoiSec please try it out - Thanks!

### CODE REVIEW

**Comment by sushi30** [comment]
this works for me in both headless and non-headless mode.

**Comment by esakal** [comment]
@eshaham can you please review this one, it is a small yet important adjustment of the flow

@brafdlog I suggest that once it will be merged you will update caspion app with this version, hopefully it will help your users

**Review by eshaham — APPROVED** [review]

**Comment by erikash** [comment]
🥳 
Well done @esakal and @sushi30!

**Comment by erikash** [comment]
@esakal do we still need the `await page.waitFor(1000);`?

**Comment by esakal** [comment]
@erikash I believe we do as they address two different issues if I'm not mistaken. Before we waited for a second, it never worked with a headless browser. While diagnostic the problem I saw in the failed snapshot that we didn't even transmit the request. Once we waited a second it started to work for you and me but failed for others in computers where the navigation started before puppeteer registered to the loading events.

**Pull request merged**
