### PR TITLE
Add account summary property to Hapoalim scraper

### PR DESCRIPTION
**Pull request by chilikla**
As detailed in issue #76, the scraper now adds a summary property to every account the scraper returns.
The summary structured like this:
```
{
  ...
  summary: {
    balance: double,
    creditLimit: double,
    creditUtilization: double,
    balanceCurrency: 'ILS',
  }
  ..
}
```
(It seems the branch was behind of master branch, and this PR adds all the commits committed since then, along with this commit. You can delete them if it needed).

### CODE REVIEW

**Comment by eshaham** [comment]
@chilikla can you please merge changes from the `upstream/account_summary` branch to your forked branch? There seem to be many unrelated commits in this PR, making it hard to review

**Comment by chilikla** [comment]
@eshaham, please help me through this, since this is my first GitHub project I'm contributing to.
I committed all these commits, since `upstream/account_summary` was way behind the `master` branch, and I thought maybe it's better make it straight ("לישר קו") and then commit the account summary (there were multiple changes since then). So the last commit is indeed the unique contribution to the branch.
If I should make it differently, please explain me how, and I will revert the changes and recommit them.

**Comment by eshaham** [comment]
@chilikla yes, that may explain this issue. 
I'm assuming you've setup your fork as described [here](https://help.github.com/articles/configuring-a-remote-for-a-fork/), and so `upstream` would be the name of the remote for the parent (my) repo.
Let's try the following:
```bash
# check out your local branch
git checkout account-summary

# rename it so we don't use it
git branch -m account-summary-old

# fetch all upstream repo changes
git fetch upstream

# checkout the latest version of the account_summary branch
git checkout account_summary

# cherry pick the specific commit for the change you wanted to make
git cherry-pick d6d186c

# push this branch to the origin of your fork
git push -u origin account_summary
```

Then create a new PR 😄 
Hope this helps.

Once completed, you can of course delete the old branch to cleanup

```bash
git branch -d account-summary-old
git push origin :account-summary
```

**Comment by chilikla** [comment]
This was a faulty PR, a fixed new one was created #103

**Pull request closed without merging**
