### PR TITLE
Add GithubAction for CI

### PR DESCRIPTION
**Pull request by baruchiro**
Configurations for using [*Github Actions*](https://github.com/features/actions) as CI service.

The *Github Actions* will run the script `test:ci` in dockers according to the `matrix`.

The `matrix` defines both **OS** and **Node version**, so for each OS and version combination, there will be a **docker container** to run the `test:ci`.

Of course, it will only run the tests that don't require login information. It's not perfect, but it can be a start.

### CODE REVIEW

**Comment by eshaham** [comment]
@baruchiro can you add to the description what this code does?

**Comment by baruchiro** [comment]
@eshaham Updated.

**Comment by esakal** [comment]
@eshaham I cannot help with this PR since I don't have access to github actions for this repo. Can you please handle this one?

**Comment by baruchiro** [comment]
https://github.com/eshaham/israeli-bank-scrapers/actions?workflow=Node+CI

First of all, it triggered on `push`, but probably not on `pull-request` or something, so if I pushing to my Pull Request it will not be triggered.

About the credentials- if there are no credentials, it will still run the "Login Fail" tests?

Anyway, I don't know yet if with GithubAction you can provide encrypted credentials, say your credentials, but I know [you can do this with TravisCI](https://docs.travis-ci.com/user/environment-variables/#defining-encrypted-variables-in-travisyml).

**Pull request merged**
