### PR TITLE
Maybe fix balance issue in beinleumi when has multiple pages for transactions

### LINKED ISSUE #610: GENERIC: Error: failed to find element matching selector ".main_balance" when scraping beileumi
When using the beinleumi scraper:

```
GENERIC: Error: failed to find element matching selector ".main_balance"
```

Checking with UI it appears the main balance indeed goes missing after the first page.

## Frist page
image

## Second page
image

### PR DESCRIPTION
**Pull request by esakal**
@sushi30 as I don't have beinleumi I cannot test this pull request. But maybe based on what you showed this might be the solution.

Please pull the PR and run the tests.

closes #610

### CODE REVIEW

**Comment by sushi30** [comment]
this works for me

**Comment by erikash** [comment]
@esakal great stuff :)
Works for me too!

**Comment by esakal** [comment]
@eshaham please see comments from @sushi30 and @erikash - it seems to resolve the broken experience. Can you please review and approve?

@sushi30 @erikash once approved I'll be able to merge it.

**Comment by erikash** [comment]
@eshaham @esakal bumping this up :)

**Comment by esakal** [comment]
@erikash hi, since I opened the PR I cannot technically approve and merge it (we have a policy for at least one reviewer). 

@eshaham can you please approve it so I'll be able to merge it?

**Review by eshaham — APPROVED** [review]

**Pull request merged**
