### PR TITLE
chargedCurrency for Isracard

### PR DESCRIPTION
**Pull request by asfktz**
related to #80

### CODE REVIEW

**Comment by esakal** [comment]
@asfktz Hi,
I don't think any scraper currently support `chargedCurrency` field. I don't see any mentioning about it in [CONTRIBUTING.md](https://github.com/eshaham/israeli-bank-scrapers/blob/master/CONTRIBUTING.md) file. Is this a new suggestion? 

Since it currently returns the same value as the original currency and other scrapers don't handle such a field, I'm not sure if we should add it for now. We can obviously consider adding such a field officially if most of the scrapers exposes that value.

@eshaham @asfktz  wdyt?

**Comment by asfktz** [comment]
Hi @esakal 👋

It's related to this issue https://github.com/eshaham/israeli-bank-scrapers/issues/80

**Comment by eshaham** [comment]
@asfktz @esakal looking back at #80, I now remember that **a**, we created a dedicated branch `charged-currency`, although it only has documentation, and **b**, it's not really clear (even in Isracard's case) that the transaction was charged in the original currency.
While there's definitely a need, I'm not sure we can really support it across the scrapers.
Question is, do you guys think we should try to do our best to support it anyway?

**Comment by esakal** [comment]
@eshaham I agree that it is not that obvious feature to implement across all scrapers, mostly because the contributors seems to charge transactions in local currency (ILS) so it will be difficult to integrate it to all our scrapers and maintain it. 

Just to point out that we already have pending support for Leumi card as well here #155. I did it back in the days when I charged my cards with foreign currency and needed it to reconsolidate my accounts.

I do think that we need to have a better adaption strategy that will allow gradually feature adoption by marking some features as optional. That way any contributor will be able to extend the library and have it available in production in no time instead of ignoring them due to lack of support in other scrapers. The `readme.md` file should be extended to include a feature-scraper support matrix, encouraging contributors to extend the library where possible, something as followed:

| Feature | Bank Hapoalim | Bank Leumi |  Bank Discount | Bank Otsar Hahayal | Visa Cal |  Leumi-Card | Isracard | Amex |
| --- | :---: | :---: | :---: | :---: | :---: | :---: | :---: | :---: |
| Local accounts | Yes | Yes | Yes | Yes | Yes | Yes | Yes | Yes | Yes |
| Installments | Yes | Yes | Yes | Yes | Yes | Yes | Yes | Yes | Yes |
| Pending Status | Yes | Yes | Yes | Yes | Yes | Yes | Yes | Yes | Yes |
| Charged currency | **No** | **No** | **No** | **No** | **No** | **No** | Yes | Yes | **No** |

This is only an example, obviously can make it more attractive by replacing the `yes` `no` text with visual icon. The point is that we will be more flexible in adding new features by saying that some features are must have in all scrapers while others are optional.

wdyt?

**Comment by asfktz** [comment]
> I do think that we need to have a better adaption strategy that will allow gradually feature adoption by marking some features as optional.

@esakal I like that! 👍 


> looking back at #80, I now remember that a, we created a dedicated branch charged-currency, although it only has documentation, and b, it's not really clear (even in Isracard's case) that the transaction was charged in the original currency.
While there's definitely a need, I'm not sure we can really support it across the scrapers.
Question is, do you guys think we should try to do our best to support it anyway?

It's a valuable property to have in my option.
I'm a bit concern that the charged currency is actually not available for us in Isracard and we provide from data (originalCurrency instead) https://github.com/eshaham/israeli-bank-scrapers/issues/80#issuecomment-509014942, see why [here](https://github.com/eshaham/israeli-bank-scrapers/issues/80#issuecomment-504664505).

Maybe it's better to wait with the Isracard implementation for now?

In the meantime time, can we implement the currency convetion for Isreali-ynab-updater 
using original currency instead until we figure out what to do?

The implementation is ready, I only need to fix conflicts with master.
https://github.com/eshaham/israeli-ynab-updater/pull/26

**Pull request closed without merging**
