### PR TITLE
max: move to the new login page

### LINKED ISSUE #533: Max scraper - Login pages now redirects to new login pages resulting in an error
The max login page that is being used (https://online.max.co.il/Anonymous/Login/CardholdersLogin.aspx) is no longer active and is being redirected to https://www.max.co.il/login 
This change results in the following error:
`waiting for selector "#PlaceHolderMain_CardHoldersLogin1_btnLogin" failed: timeout 30000ms exceeded`

### PR DESCRIPTION
**Pull request by baruchiro**
close #533

### CODE REVIEW

**Comment by esakal** [comment]
I'm getting this view, let's wait to see if it changes or if it is permanent `https://online.max.co.il/login`

image

**Comment by erikash** [comment]
Hi,
I cloned @baruchiro repo and ran `npm test` after filling in my credentials in `test-config.js` and the scaper didn't work for me.

See screenshot and output:
image

```
erik.a@ErikAshepa:~/Projects/israeli-bank-scrapers (master)$ npm test

> israeli-bank-scrapers@1.0.0 test /Users/erik.a/Projects/israeli-bank-scrapers
> cross-env BABEL_ENV=test jest

 PASS  src/scrapers/discount.test.ts
 PASS  src/scrapers/otsar-hahayal.test.ts
 PASS  src/scrapers/visa-cal.test.ts
 PASS  src/scrapers/hapoalim.test.ts
 PASS  src/scrapers/mizrahi.test.ts
 PASS  src/scrapers/leumi.test.ts
 PASS  src/scrapers/beinleumi.test.ts
 PASS  src/scrapers/isracard.test.ts
 PASS  src/scrapers/amex.test.ts
 PASS  src/scrapers/union-bank.test.ts
 PASS  src/scrapers/base-scraper-with-browser.test.ts
 FAIL  src/scrapers/max.test.ts (23.249s)
  ● Max scraper › should scrape transactions"

    expect(received).toBe(expected) // Object.is equality

    Expected: ""
    Received: "TIMEOUT waiting for redirect from https://www.max.co.il/login"

      45 |     expect(result).toBeDefined();
      46 |     const error = `${result.errorType || ''} ${result.errorMessage || ''}`.trim();
    > 47 |     expect(error).toBe('');
         |                   ^
      48 |     expect(result.success).toBeTruthy();
      49 |
      50 |     exportTransactions(COMPANY_ID, result.accounts || []);

      at Object.<anonymous> (scrapers/max.test.ts:47:19)

Test Suites: 1 failed, 11 passed, 12 total
Tests:       1 failed, 21 skipped, 12 passed, 34 total
Snapshots:   0 total
Time:        24.223s, estimated 27s
Ran all test suites.
A worker process has failed to exit gracefully and has been force exited. This is likely caused by tests leaking due to improper teardown. Try running with --runInBand --detectOpenHandles to find leaks.
npm ERR! Test failed.  See above for more details.
erik.a@ErikAshepa:~/Projects/israeli-bank-scrapers (master)$
```

**Comment by baruchiro** [comment]
I will check this next week.

But the page seems very simple, they gave `id` to all important elements 🙂.

Just note there are duplicate `id`s, so make sure you're using an unique selector

**Comment by erikash** [comment]
I hope you did.. because I cloned your code @baruchiro :)
I'll try to debug it a bit...

**Comment by erikash** [comment]
I was blocked too :(

@baruchiro it seems that there is some Loader which causes a race condition after: `await clickButton(this.page, '#login-password-link');` inside the `loginOptions.preAction` so at least for me the credentials are not getting filled by `await this.fillInputs(loginOptions.fields);`

**Comment by erikash** [comment]
@esakal the url: `online.max.co.il/login` is valid.. after a few runs I was blocked and received the same page as you :)

**Comment by erikash** [comment]
@baruchiro , I've figured it out.. we need to wait until `app-user-login-form` is visible:
```
preAction: async () => {
        if (await elementPresentOnPage(this.page, '#closePopup')) {
          await clickButton(this.page, '#closePopup');
        }
        await clickButton(this.page, '#login-password-link');
        await waitUntilElementFound(this.page, '#login-password.tab-pane.active app-user-login-form', true);
      },
```

**Comment by esakal** [comment]
handled as part of #536

**Pull request closed without merging**
