### PR TITLE
Fix visa cal scraper

### PR DESCRIPTION
**Pull request by ifeins**
This fixes the following issue - https://github.com/eshaham/israeli-bank-scrapers/issues/140

The date calculation was done incorrectly, so I changed it to use moment.js

### CODE REVIEW

**Comment by ifeins** [comment]
@eshaham @esakal @nirgin Please review

**Comment by eshaham** [comment]
@ifeins nice catch 😄

**Comment by ifeins** [comment]
@eshaham @esakal Thanks for merging. Can you publish a new version of `israeli-bank-scrapers` and `israeli-ynab-updater`?
This is affecting all Visa Cal users.

**Comment by eshaham** [comment]
@ifeins [done](https://github.com/eshaham/israeli-bank-scrapers/releases/tag/v0.6.1).
Updater tool also updated.

**Pull request merged**
