### PR TITLE
Remove bank hapoalim be online

### PR DESCRIPTION
**Pull request by orzarchi**
Seems like bank hapoalim merged their login portals, and I can scrape my be online account using the regular scraper.
I've removed the now obsolete "be online" code.

### CODE REVIEW

**Comment by orzarchi** [comment]
@esakal @eshaham it's a really simple change :)

**Comment by esakal** [comment]
Hi, @orzarchi I will try to escalate this one

**Comment by eshaham** [comment]
@orzarchi so sorry for the delay
@esakal don't we want to obsolete it instead of just deleting as we did in https://github.com/eshaham/israeli-bank-scrapers/pull/348?

**Comment by esakal** [comment]
@eshaham we can make it obsolete instead. @orzarchi can you do the adjustments based on #348 ? Once done we will be able to merge it in no time. Sorry for the delay.

**Comment by orzarchi** [comment]
@esakal I've restored a clause to the `createScraper` function with a warning. Any other adjustment I missed?

**Pull request merged**
