### PR TITLE
add POSTPONED_TRANSACTION_INSTALLMENTS to max

### LINKED ISSUE #529: Missing MAX transaction type
Hi,
Scrapping a max card I received a new tx type that is missing in max.ts
"פריסת העסקה הדחויה"

### PR DESCRIPTION
**Pull request by esakal**
echo the change of #530 without running prettier on the max scraper and verify that eslint passes.

@gczobel your IDE is probably running Prettier with different set of rules which breaks our eslint tests and also present more changes then needed. see https://github.com/eshaham/israeli-bank-scrapers/pull/530/files

for example: 
```
/Users/eransakal/dev/github/eshaham/israeli-bank-scrapers/src/scrapers/max.ts
  44:44  error  Strings must use singlequote  @typescript-eslint/quotes
```

Please let me know if this PR work and if so we will merge this one instead.

closes #529 #530

---
This change is [Reviewable](https://reviewable.io/reviews/eshaham/israeli-bank-scrapers/531)

### CODE REVIEW

**Comment by gczobel** [comment]
My VSCode is running prettier... I forgot to check the diff for other changes.
Yes, this version is ok. I closed my PR.

Thanks!

**Comment by esakal** [comment]
@eshaham please review and approve (I cannot merge it as I opened the review and I don't have permissions to bypass it

**Comment by esakal** [comment]
@eshaham please review and approve

**Review by eshaham — APPROVED** [review]

**Comment by esakal** [comment]
@eshaham please release a new official version when possible.

@gczobel In the meanwhile feel free to pull the next tag from npm:

```
npm i israeli-bank-scrapers@next
```

**Comment by esakal** [comment]
@gczobel it seems that we have a problem with the automatic process that release next version. you can track the status here #525 and I assume Elad will release an official version sometime soon anyway.

**Pull request merged**
