### PR TITLE
Max login

### LINKED ISSUE #533: Max scraper - Login pages now redirects to new login pages resulting in an error
The max login page that is being used (https://online.max.co.il/Anonymous/Login/CardholdersLogin.aspx) is no longer active and is being redirected to https://www.max.co.il/login 
This change results in the following error:
`waiting for selector "#PlaceHolderMain_CardHoldersLogin1_btnLogin" failed: timeout 30000ms exceeded`

### PR DESCRIPTION
**Pull request by esakal**
@erikash @baruchiro I created a new PR with your code and adjusted it - it seems to work now:
1. use the welcome page as the direct login is being blocked after few attempts
2. use `checkReadiness` to decide when we can open the login modal
3. open the modal from the header which should (hopefully) always work as this is the welcome page

@erikash @baruchiro Please review

@eshaham  please also review and approve so we will be able to merge it to master asap.

close #533, close #534

### CODE REVIEW

**Review by baruchiro — APPROVED** [review]
I ran the test 10 times in a row and everything was fine.

**Comment by erikash** [comment]
Looks good 👍

**Comment by tpseven-777** [comment]
Are you guys going to release a new version with this fix soon? Is there anything I can do to help this happen?

**Review by eshaham — APPROVED** [review]
@esakal looking good to me!

**Comment by ifeins** [comment]
@esakal Thanks for the fix 👍 

One question though, I see that the `@next` version was published 1 month ago: https://www.npmjs.com/package/israeli-bank-scrapers/v/next

Shouldn't it be published by the CI every time that a branch is merged to master?

**Comment by baruchiro** [comment]
Yes, we are waiting for the next version!

**Comment by ifeins** [comment]
@baruchiro From what I understood the `next` tag should be published automatically every time a change is pushed to `master` branch: https://github.com/eshaham/israeli-bank-scrapers#getting-deployed-version-of-latest-changes-in-master

However it seems that the next version was published one month ago: https://www.npmjs.com/package/israeli-bank-scrapers/v/next so to me it seems that there might be something wrong with the CI because I expected the `next` version to be published yesterday (this MR was merged yesterday).

**Comment by esakal** [comment]
@ifeins  you are right about next tag, it should be deployed automatically and immediately. It seems that there are issues with the NPM credentials defined in the secrets of this project. @eshaham will probably fix it soon.

**Comment by esakal** [comment]
@ifeins @baruchiro until we will solve the automation process I manually deployed the next version of israeli-bank-scrapers [here](https://www.npmjs.com/package/israeli-bank-scrapers/v/next) you can install it as usual using `npm install israeli-bank-scrapers@next`.

I couldn't publish the core version as at the moment I don't have publish permission to that package in npm, so if you are using the core version you will have to wait for @eshaham to deploy the latest version

**Comment by ifeins** [comment]
@esakal Can you elaborate what are the problems with the automation process?
Maybe I can help.

P.S.
Possibly we can discuss this in a separate thread (e.g. a dedicated github issue for the automation process) and not in the PR.

**Comment by esakal** [comment]
@ifeins thanks, we actually managed to resolve it. We enabled 2FA in NPM to protect against someone who steal our credentials and deploy malicious version. By doing so the automatic process stopped working as 2FA basically requires interactive deployment. But since Oct 2, NPM shipped a feature that address exactly that and lets you create automation token which doesn't require 2FA and now we can enjoy both worlds. 

Also, we plan to automate the release of the official versions by using semantic releases or something similar which means that once pushed to master it will be available immediately as official release and not pre-release

**Pull request merged**
