### PR TITLE
feat(mizrahi-scraper): new site support

### LINKED ISSUE #668: Mizrahi scrapper is no longer working after site changes
It seems like Mizrahi has a new site (not sure if it's a rollout or 100% live, can you confirm?)
now Mizrahi scrapper is no longer working due to selectors/URL changes and probably some CSR changes
Screen Shot 2022-03-23 at 2 26 59

### PR DESCRIPTION
**Pull request by Asafb26**
Resolves #668

@esakal @eshaham  FYI

### CODE REVIEW

**Comment by esakal** [comment]
@Asafb26 I don't have mizrahi account to verify it. Can I assume it is relevant to all types of accounts?

**Comment by esakal** [comment]
@Asafb26 @naorpeled thanks, can you please coordinate this one and let me know when I can merge it?

**Comment by Asafb26** [comment]
@naorpeled it looks like they changed the url once again, now not contains "pilot". do you still see the old site?

**Comment by naorpeled** [comment]
> @naorpeled it looks like they changed the url once again, now not contains "pilot". do you still see the old site?

I see the new one when going into the Hebrew version of the site,
I still see the old one when going into the English one though.

What do you think about adding something like
 `page.$x(`//a//*[contains(text(), 'עובר ושב') or contains(text(), 'Checking Account')]`)`


to be a bit less specific and more future proof?

**Comment by baruchiro** [comment]
Hi, can I help? Are you still working on it?

**Comment by esakal** [comment]
@naorpeled sorry I don't have an answer because I don't have this kind of account and I don't really know what is happening there.
But if your change is relevant to everyone then we are covered. Unless @Asafb26  saw that for him it breaks because of account type or anything else.. @Asafb26  can you update?

@baruchiro if you have account there maybe you can assist by checking it as well.

**Comment by dumsky** [comment]
Guys any news regarding the Mizrahi PR?

**Comment by naorpeled** [comment]
> Guys any news regarding the Mizrahi PR?

I'll work on it

**Comment by naorpeled** [comment]
> Guys any news regarding the Mizrahi PR?

I played with the code a bit,
didn't manage to get it to work yet and I don't have enough time to continue working on it atm unfortunately.

**Comment by Asafb26** [comment]
I'm not sure how long Mizrahi provide the old site in English, maybe for simplicity, we can provide a dedicated English scraper for Mizrahi (aka a full copy of the old scraper) for now?
@esakal I tried 2 different Mizrahi accounts, both of them pointed on the new site in Hebrew and the old one in English

**Comment by dumsky** [comment]
> I'm not sure how long Mizrahi provide the old site in English, maybe for simplicity, we can provide a dedicated English scraper for Mizrahi (aka a full copy of the old scraper) for now? @esakal I tried 2 different Mizrahi accounts, both of them pointed on the new site in Hebrew and the old one in English

Is there a way to tell the scrapper now to work in the english version?

**Comment by esakal** [comment]
@Asafb26 I'm not sure that I follow the current status of Mizrahi. few questions:
1. when you run the scrapper deployed it fails to all accounts?
2. when you run the scrapper in this PR does it work? is it good for all accounts or some accounts still need the existing scrapper?

@naorpeled said that the PR version doesn't work for him, is it because he has different account? If that is the case, can we extend the existing scrapper and create a wrapper that check which type of account it is and based on that will either run the existing scrapper content or the one of this PR?

**Comment by dumsky** [comment]
@Asafb26 I think I've made it work:

async fetchData() {
        await this.page.$eval('#dropdownBasic, .item', (el) => (el).click());
        const numOfAccounts = (await this.page.$$(accountDropDownItemSelector)).length;

        try {
            const results = [];
            for (let i = 0; i < numOfAccounts; i += 1) {
                **if (i > 0) {
                    await this.page.$eval('#dropdownBasic, .item', (el) => (el).click());
                }

                await this.page.$eval(accountDropDownItemSelector + ":nth-child(" + (i + 1) + ")", (el) => (el).click());**
                results.push((await this.fetchAccount()));
            }

            return {
                success: true,
                accounts: results
            };
        } catch (e) {
            return {
                success: false,
                errorType: _baseScraper.ScraperErrorTypes.Generic,
                errorMessage: e.message
            };
        }
    }

**Comment by dumsky** [comment]
@Asafb26 I made it work with multiple accounts"

`
async fetchData() {
        await this.page.$eval('#dropdownBasic, .item', (el) => (el).click());
        const numOfAccounts = (await this.page.$$(accountDropDownItemSelector)).length;

        try {
            const results = [];
            for (let i = 0; i < numOfAccounts; i += 1) {
                if (i > 0) {
                    await this.page.$eval('#dropdownBasic, .item', (el) => (el).click());
                }

                await this.page.$eval(accountDropDownItemSelector + ":nth-child(" + (i + 1) + ")", (el) => (el).click());
                results.push((await this.fetchAccount()));
            }

            return {
                success: true,
                accounts: results
            };
        } catch (e) {
            return {
                success: false,
                errorType: _baseScraper.ScraperErrorTypes.Generic,
                errorMessage: e.message
            };
        }
    }`

**Comment by esakal** [comment]
@dumsky  @Asafb26 let me know when you the code works and you need me to deploy a version

**Comment by naorpeled** [comment]
Made a new PR that combines the code of @Asafb26 and @dumsky, with a small change that resolved an issue I've encountered:
https://github.com/eshaham/israeli-bank-scrapers/pull/673

@Asafb26 feel free to update your PR with the code in mine,
wasn't sure wether to create a new PR or not.

**Comment by esakal** [comment]
@Asafb26 please see my last comment in #673

**Pull request closed without merging**
