### PR TITLE
Typescript

### LINKED ISSUE #152: Typescript
what do you think about moving to Typescript?

### LINKED ISSUE #487: Support Typescript - Contributors Call To Action
Hi All,

As you probably saw in the last few months we worked on a PR that will add Typescript support to our codebase. All the companies and utils were migrated to use Typescript in this pr #404.

# Call to action - testing all companies with the typescript support

> We should try and finalize it this week so we will be able to start August with static type checks guarding us and letting us be more relaxed during this full-parenting-month.

**WE NEED YOUR HELP!** making sure all the companies work as expected. 

The table below list all the 
I mentioned below the creator of each company, even if you are not a creator if you managed to test more companies please add a comment and I will update the table accordingly. 

|  Company | Creator  | Tested by 
|---|---|---|
|  Bank Hapoalim | @sebikaplun  | @esakal  |   
|  Leumi Bank | @esakal  |  @esakal, @baruchiro    |   
|  Discount Bank |   | @brafdlog  |   
|  Mizrahi Bank |  @baruchiro  | @baruchiro  |   
|  Otsar Hahayal Bank |  @matanelgabsi    |   |   
|  Visa Cal |   @nirgin   | @brafdlog,  @esakal    |   
|  Max |   |   @esakal, @baruchiro   |   
|  Isracard |   | @baruchiro, @esakal   |   
|  Amex |  @erezd   |  @esakal  |   
|  Union Bank |   @dratler,@kalinoy,@shanigad,@dudiventura and @NoamGoren  |   |   
|  Beinleumi | @dudiventura   |   |   

(*) Hopefully at least two contributors will confirm each company, although one will be accepted as well.

**Please use the following guide to test the companies that you have and drop a comment with the list of companies you tested. If it fails on one or more of them add the compilation error in the comment.**

- [ ] Make sure you don’t have any uncommitted changes.
- [ ] Check out the `typescript` branch
```
git pull
git checkout typescript
```
- [ ] delete `node_modules` folder 
- [ ] install dependencies `npm install`
- [ ] build the repo and make sure you don’t get any Typescript compile errors `npm run build`
- [ ] create the tests configuration file with your credential. Duplicate file `./src/tests/tests-config.tpl.js` -> `./src/tests/tests-config.js` 
- [ ] assign a valid path in the test configuration file under `excelFilesDist` property.
- [ ] add your credentials in the test file.
- [ ] run the tests `npm run test`

**Acceptance criteria:**
The library builds successfully 
All the companies you have created a valid excel file (meaning all the fields you expect to see there actually exist).

---

Thank you all for helping with this one. We hope the Typescript support will let us do great things with this library.

@eshaham, @esakal

### PR DESCRIPTION
**Pull request by esakal**
# Goals
Use Typescript with israeli-bank-scrapers library.

@eshaham since this PR is going to have several iterations, please review and comment using reviewable (use the button at the bottom of this description to redirect to reviewable)

# Motivation
As we are looking toward making this library extendible and customizable, we expect the library api to grow and we would like to use Typescript to help us to scale.
[read more](https://medium.com/@jtomaszewski/why-typescript-is-the-best-way-to-write-front-end-in-2019-feb855f9b164)

# Tasks
- [x] add Typescript dependencies & configuration.
- [x] use Babel & Typescript during build process.
- [x] convert all helpers to Typescript.
- [x] convert constants to Typescript and use enums.
- [x] add core type declaration for Transaction, LoginResult, and others.
- [x] update (jest) tests infrastructure to use Typescript.
- [x] convert Leumi account to Typescript.
- [x] fix lint warnings.
- [x] remove test folder as part of the building process
- [x] convert all remaining files from js to ts.
- [x] fix type of LoginOptions > possibleResults
- [x] run local test on available companies
- [x] update documentation.
- [x] make sure external apps works with this library.
- [x] make sure external apps works with this library **in core mode**.
- [x] ask developers to test their companies as well.

closes #152
closes #487 

---
This change is [Reviewable](https://reviewable.io/reviews/eshaham/israeli-bank-scrapers/404)

### CODE REVIEW

**Comment by esakal** [comment]
@eshaham when possible please review using [Reviewable](https://reviewable.io/reviews/eshaham/israeli-bank-scrapers/404). I have put this one on hold till you review the first drop so you will not have too many changes to review at once.

**Comment by eshaham** [comment]
already started reviewing on reviewable, just haven't submitted anything

**Comment by brafdlog** [comment]
What is the status of this pr? Is there something to be done that you need help with?

**Comment by brafdlog** [comment]
I think the the ScraperScrapingResult type and the Transaction type are not currently exported in a way that they can easily be used in the calling code. IMO they should be exposed to allow working with those types easily.

**Comment by eshaham** [comment]
@esakal what a huge milestone 💪 
thanks so much for pushing and driving this change!!!

**Pull request merged**
