### PR TITLE
Add transaction status

### LINKED ISSUE #57: Status property
Sometimes, recent transactions may change.

For example, in Bank Hapoalim, transactions above the fold are still `"pending"`:
screen shot 2018-01-25 at 9 30 46 pm

Having a `status` field will be useful to differentiate between `pending` and `posted` transactions

Example for `Bank Hapoalim`:

```js
status: txn.serialNumber === 0 ? 'pending' : 'posted'
````

### PR DESCRIPTION
**Pull request by eshaham**
Adds either a `completed` or a `pending` status field to all transactions

closes #57

### CODE REVIEW

**Comment by eshaham** [comment]
@asfktz please go over before I merge 😄

**Comment by asfktz** [comment]
Hi @eshaham, nice!
I will soon

**Comment by eshaham** [comment]
@esakal can you add transaction status to Leumi scraper as well?

**Comment by esakal** [comment]
@eshaham sure I will check this out, should I open a separated PR for that?

**Comment by asfktz** [comment]
@eshaham looks good to me (:

**Comment by eshaham** [comment]
@esakal did you get a chance to take a look?

**Comment by esakal** [comment]
Hi @eshaham, Actually I didn't I was working on eshaham/israeli-ynab-updater#32 which consumed most of my time in the last two weeks. Hopefully I will be able to check it later this week.

**Comment by esakal** [comment]
@eshaham can you please merge master into this branch. It doesn't seems to include the bank leumi scraper

**Comment by esakal** [comment]
@eshaham I'm not sure what should I do to get pending transactions. I was entering my account several times during the week and the weekend without success.

Do you know when a pending transaction is being created?

**Comment by eshaham** [comment]
@esakal it is usually created when the bank has knowledge of a future transaction. The most common use case is when you have credit cards under your bank account, and the bank shows a future pending transaction for the monthly charge. They may appear under a separate menu item in your checking account. If you don't see these under your account, maybe Leumi doesn't have them listed?? @ifeins, can you check in your account?

**Comment by asfktz** [comment]
@eshaham, In Bank Hapoalim, it looks something like this:

35408496-ffbbd098-0217-11e8-9a99-217d635caf47

**Comment by esakal** [comment]
@asfktz @eshaham  thanks, I understand it should appear around the credit card payments. I will try to access it tomorrow hopefully to see something similar

**Comment by esakal** [comment]
@eshaham can you please merge master to this branch because Leumi scraper is not [there yet](https://github.com/eshaham/israeli-bank-scrapers/tree/txn_status/src/scrapers)

Let me know if you want that I will merge master into this branch

**Comment by eshaham** [comment]
@esakal done

**Comment by esakal** [comment]
@eshaham please review  #107

**Comment by eshaham** [comment]
@esakal done. Thanks!!

**Pull request merged**
