### PR TITLE
chore: restore lint status check which is blocking merges

### PR DESCRIPTION
**Pull request by esakal**
@eshaham at the moment due to the orphaned status check `lint` that blocks all PRs I cannot merge approved ones like #593 

As I didn't find a way to get rid of this status check, I though maybe it is easier to just add it again so it will hopefully resolve the blocker we currently have on any PRs.

### CODE REVIEW

**Comment by baruchiro** [comment]
In my opinion, we have to run `lint` on PR.

**Comment by esakal** [comment]
@baruchiro we run lint on any PR as part of another workflow https://github.com/eshaham/israeli-bank-scrapers/blob/f083975993052c9d8b21bec464fbebbae300dd07/.github/workflows/nodeCI.yml#L22

There is no point running the lint also separately. But because the technical issue I mentioned, I'm moving the lint test back to a separate workflow.

**Comment by baruchiro** [comment]
OK. It is not a technical issue, I think. It is just @eshaham need to remove the "required" from this status check.

**Comment by esakal** [comment]
@eshaham please review, it blocks all the other PRs.

**Comment by esakal** [comment]
@eshaham  can you help with that one?

**Review by eshaham — APPROVED** [review]
@esakal sorry tough couple of weeks, approving and merging

**Pull request merged**
