### PR TITLE
chore: upgrade typescript

### PR DESCRIPTION
**Pull request by chellem**
Main Upgrade:

`typescript` 3.9.10 => 4.9.5

and for compatibility purpose, upgrade of the following dependencies of:

- `jest`
- `ts-jest`
- `babel-jest`

### CODE REVIEW

**Comment by esakal** [comment]
@chellem thank you for your contribution. I wonder if upgrading Typescript is considered as breaking change? What was the motivation for the upgrade? how did it impact you?

Two minor issues:
1. can you please remove the newly added yarn.lock file? the project is using npm (thus package-lock.json)
2. in some places you bypass Typescript by using `e as Error` or `rawTransaction as XYZ`. Is it needed? usually Typescript resolve the type for you and you don't need to do a bypass.

**Comment by chellem** [comment]
Motivation: Feel that there was a need for an [upgrade](https://github.com/eshaham/israeli-bank-scrapers/issues/758) 

1. Remove `yarn.lock`
2. It's not a bypass, it's [type casting](https://stackoverflow.com/questions/54649465/how-to-do-try-catch-and-finally-statements-in-typescript).

**Comment by esakal** [comment]
@chellem I see you closed the PR, do you want to re-open it or you closed it on purpose? 

The only question I have about the PR is about the usage of `e as Error` and `as undefined as string`. Beside that it looks good.

**Comment by chellem** [comment]
@esakal do you have other suggestions that can be used instead of `e as Error` ?

**Pull request closed without merging**
