### PR TITLE
fix(scrapers/leumi): support logging in to business account

### PR DESCRIPTION
**Pull request by etdegani1**
Changed the element waited for on PostLogin to be compatible with personal as well as business account landing page

### CODE REVIEW

**Comment by etdegani1** [comment]
Hi @esakal How can I merge this PR? Logging in to business account in leumi is currently broken because of a different main screen post-login, so I've changed the element being waited for to a one that exists in all account types i've checked, and only in case of success....

**Comment by etdegani1** [comment]
@esakal ?

**Comment by esakal** [comment]
@etdegani1 sorry for not responding sooner. Paradoxically, it is faster for me to merge changes in scrappers that I don't have access to because I don't have a way to test it, as opposed to changes in scrappers like Leumi where I do have access and I need to find sometime to test them.

I'm on it

**Comment by esakal** [comment]
@etdegani1 sorry again for the delay and thank you for your patience

**Comment by baruchiro** [comment]
Hi @etdegani1, [Call for Code Owners](https://github.com/eshaham/israeli-bank-scrapers/issues/830) 🙏

**Pull request merged**
