### PR TITLE
Adding Identifier to visa-cal

### PR DESCRIPTION
**Pull request by omercnet**
Adding the Id property from VisaCal API to the scraped transactions

### CODE REVIEW

**Comment by omercnet** [comment]
@esakal @maorsom could you take a look?

**Review by eshaham — APPROVED** [review]
Nice 💪 
thanks @omercnet 🙏

**Comment by omercnet** [comment]
bekef :)

would appreciate a patch release so I can use the official library in my project

**Comment by omercnet** [comment]
actually please hold, another push to max on the way

**Comment by esakal** [comment]
@omercnet Hi!
Since @eshaham already merged this PR, can you create a new one based on the latest master that holds your previous changes?

**Comment by esakal** [comment]
> would appreciate a patch release so I can use the official library in my project

@omercnet just to be sure you are familiar with this option. we release automatically a version when pushing to master and deploy it to NPM with tag `next`.

```
npm i israeli-bank-scrapers@next
```

**Comment by omercnet** [comment]
> @omercnet Hi!
> Since @eshaham already merged this PR, can you create a new one based on the latest master that holds your previous changes?

yes of course, I meant hold off before the patch release :)

**Comment by sagiba** [comment]
Note that the Id attribute by itself is not unique for installment transactions on visa cal.
I've been using the following combo successfully for years now:
```javascript
txn.identifier = `${raw.Id}:${raw.Numerator}`;
```

**Comment by esakal** [comment]
@sagiba Hi
the identifier represents אסמכתא which isn't unique in most companies. For example in bank Leumi you will get the same identifier for every transaction that transfer money to your credit card of leumi card.

what you did will create a unique identifier but is not אסמכתא.

**Comment by sagiba** [comment]
@esakal interesting, what is the אסמכתא alone used for though, if not for uniquely identifying a transaction?

I think it will be super useful for the library to also return a unique ID for each transaction (I already depend on this in my project, to sync with an internal database), but this is discussion is probably worthy of a separate issue.

**Pull request merged**
