### PR TITLE
use proper typescript support in core version

### LINKED ISSUE #518: Puppeteer types are imported from the puppeteer package instead of puppeteer-core
In the `israeli-bank-scrapers-core` package, in the `next` version (`0.9.2-dev.83c4b6641`), there are imports of types from `puppeteer` instead of `puppeteer-core`. This causes compilation errors, see:

Screen Shot 2020-09-09 at 15 00 33

### PR DESCRIPTION
**Pull request by esakal**
following #518 I improved the way switching from puppeteer to puppeteer-core and handled its typescript support.

closes #518

### CODE REVIEW

**Comment by brafdlog** [comment]
@esakal Nice! The jscodeshift solution is cool.

I checked locally by checking out this branch, running the prepare:core script and copying the result into the node_modules of my project and it worked.

The check I did does not behave exactly the same as installing the built package from npm so there is a chance there will be issues that I missed. But it looks good.

**Comment by esakal** [comment]
@brafdlog great to hear. 

@eshaham can you check this one as well and if it works for you approve the PR?

**Comment by esakal** [comment]
@eshaham the github policy doesn't let me merge this one. @brafdlog already reviewed this one and the changes doesn't affect the code itself but rather the code that prepare the core version.

Can you please merge it or approve it so he will be able to use the new version with the automatically `next` version? 

Thanks and Hag Sameach :)

**Review by eshaham — APPROVED** [review]

**Comment by brafdlog** [comment]
Thanks 🎉

**Pull request merged**
