### PR TITLE
Error handling

### PR DESCRIPTION
**Pull request by eshaham**
Some refactoring around error handling, plus fixing the annoying timeout error which wasn't really handled once and for all

### CODE REVIEW

**Comment by esakal** [comment]
The code changes looks relevant. I remember that we have an issue with an error not being propagated correctly but I failed to reproduce it now (don't remember the exact scenario). 

I tested both valid scenario and invalid scenario (providing false credentials to Bank Leumi) and both worked as expected. Note that we still get `generic` error type when having timeout 
```
Bank Leumi: START_SCRAPING
Bank Leumi: INITIALIZING
Bank Leumi: TERMINATING
Bank Leumi: END_SCRAPING
success: false
error type: generic
error: Navigation Timeout Exceeded: 30000ms exceeded
```

**Comment by eshaham** [comment]
@esakal 😱 
how did you reproduce the timeout?

**Comment by esakal** [comment]
The wifi on the train is poor so I usually get timeouts when scraping. I can debug this PR on Wed if you want. Another options is using https://www.charlesproxy.com/ if I remember it has an option to simulate timeout

**Comment by esakal** [comment]
@eshaham I think you should merge this pr as-is and ignore the edge case I mentioned. It seems to improve the error handling and better describe what happens.

**Comment by eshaham** [comment]
@esakal 👍  I agree

**Pull request merged**
